FROM ubuntu:22.04 as portia_dev

ARG UID
ARG GID
ARG USERNAME

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    curl \
    software-properties-common \
    apt-transport-https \
    python3-software-properties \
    ca-certificates

RUN apt-get install -y \
    nginx

ADD docker/nginx /etc/nginx

RUN apt-get install --no-install-recommends -y \
    fonts-liberation \
    ttf-wqy-zenhei \
    fonts-arphic-gbsn00lp \
    fonts-arphic-bsmi00lp \
    fonts-arphic-gkai00mp \
    fonts-arphic-bkai00mp \
    fonts-beng && \
    echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections && \
    apt-get install --no-install-recommends -y ttf-mscorefonts-installer

RUN apt-get install -y \
    pkg-config \
    netbase \
    build-essential \
    zsh \
    emacs \
    vim \
    iputils-ping \
    ripgrep \
    git \
    jq

RUN apt-get install -y --no-install-recommends \
    python3.10 \
    python3.10-dev \
    libmysqlclient-dev \
    python3-mysql.connector \
    python3-numpy \
    python3-openssl \
    python3-pip \
    python3-setuptools \
    python3-wheel   \
    python3-venv \
    python3-numpy

RUN apt-get install -y liblzma-dev \
    libncursesw5-dev \
    libsqlite3-dev \
    libreadline-dev \
    libbz2-dev \
    libffi-dev \
    libssl-dev \
    libgdbm-dev \
    zlib1g-dev \
    libjpeg-dev \
    libtiff-dev \
    libpq-dev \
    libxml2-dev \
    libxslt1-dev \
    libsdl2-dev \
    libgstreamer-plugins-base1.0-dev \
    libnotify-dev \
    freeglut3-dev \
    libsm-dev \
    libgtk-3-dev \
    libwebkitgtk-6.0-dev \
    libxtst-dev

# this is required for dev and build
# libre2 is required at runtime
RUN apt-get install -y libre2-dev

RUN apt-get install -y --no-install-recommends \
    liblua5.4-dev \
    zlib1g \
    zlib1g-dev

#TODO: is these dependencies required at runtime?
RUN apt install -y --no-install-recommends \
    qtcreator qtbase5-dev qt5-qmake \
    libqt5webkit5-dev \
    python3-pyqt5.qtsvg python3-pyqt5.qtwebkit

RUN groupadd --gid $GID ${USERNAME} && \
    useradd --uid $UID --gid $GID --create-home --shell /usr/bin/zsh ${USERNAME}

USER ${USERNAME}

RUN pip install git+https://github.com/facebook/pyre2

RUN pip install setuptools six && \
    pip install \
        qt5reactor \
        psutil \
        Twisted \
        adblockparser \
        xvfbwrapper \
        funcparserlib \
        Pillow \
        lupa \
        PyQt5-sip

RUN pip install git+https://github.com/benquike/scrapely
RUN pip install git+https://github.com/benquike/scrapy-splash.git

RUN pip install git+https://github.com/benquike/portia2code
