# Generated by Django 5.1.4 on 2024-12-21 18:35

import db_repo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objs',
            name='oid',
            field=db_repo.models.RealBinaryField(default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', max_length=40),
        ),
    ]
